# Generated by Django 5.1 on 2024-08-28 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('places', models.IntegerField()),
                ('view', models.CharField(max_length=255)),
                ('cube', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cube_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('where_from', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('transport', models.CharField(max_length=255)),
                ('current_place', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
